# Generated by Django 5.2.12 on 2026-03-30 00:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('icone', models.CharField(help_text='Classe Font Awesome (ex. fa-warehouse, fa-box).', max_length=80)),
            ],
            options={
                'verbose_name': 'catégorie de stockage',
                'verbose_name_plural': 'catégories de stockage',
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description_detaillee', models.TextField()),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(choices=[('Cotonou', 'Cotonou'), ('Porto-Novo', 'Porto-Novo'), ('Parakou', 'Parakou'), ('Bohicon', 'Bohicon'), ('Abomey-Calavi', 'Abomey-Calavi')], max_length=32)),
                ('image_principale', models.ImageField(upload_to='entrepots/')),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surface_m2', models.PositiveIntegerField()),
                ('equipements', models.JSONField(blank=True, default=list, help_text='Options : Gardiennage, Caméras, Électricité, Zone Frigo (liste JSON).')),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrepots', to='core.categoriestorage')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrepôt',
                'verbose_name_plural': 'entrepôts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('frais_assurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('qr_code_auth', models.SlugField(blank=True, help_text='Identifiant unique pour authentification QR (généré à la confirmation).', max_length=40, null=True, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_client', to=settings.AUTH_USER_MODEL)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.entrepot')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ['-date_debut'],
            },
        ),
    ]
