# Generated by Django 5.2.12 on 2026-03-31 20:43

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usercustom_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='telephone',
            field=models.CharField(blank=True, help_text='Format international E.164 (ex. +22990123456).', max_length=24, validators=[core.models.validate_telephone_e164]),
        ),
        migrations.CreateModel(
            name='EntrepotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entrepots/galerie/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.entrepot')),
            ],
            options={
                'verbose_name': 'image entrepôt',
                'verbose_name_plural': 'images entrepôt',
                'ordering': ['ordre', 'pk'],
            },
        ),
    ]
