# Generated by Django 5.2.12 on 2026-03-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entrepot_image_and_phone_e164'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriestorage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image représentative (optionnelle ; prioritaire sur l’icône sur le site).', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='categoriestorage',
            name='icone',
            field=models.CharField(help_text='Classe Font Awesome (ex. fa-warehouse, fa-box), affichée si aucune image.', max_length=80),
        ),
    ]
