# Generated by Django 5.2.12 on 2026-03-31 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categorie_storage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepotAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_espaces', to=settings.AUTH_USER_MODEL)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='core.entrepot')),
            ],
            options={
                'verbose_name': 'avis espace',
                'verbose_name_plural': 'avis espaces',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('entrepot', 'auteur'), name='unique_entrepot_avis_par_auteur')],
            },
        ),
    ]
