# Generated by Django 5.2.12 on 2026-04-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_affiner_caution_regles'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepot',
            name='boost_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fin de mise en avant.', null=True),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='is_boosted',
            field=models.BooleanField(default=False, help_text='Annonce mise en avant.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkin_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de dépôt.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkout_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de retrait.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='code_court',
            field=models.CharField(blank=True, help_text='Code d’accès court (ex. ABC-123).', max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='inventaire_photo',
            field=models.ImageField(blank=True, help_text='Photo des marchandises déposées.', null=True, upload_to='reservations/inventaires/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prochaine_echeance',
            field=models.DateField(blank=True, help_text='Date de prochaine échéance pour paiement mensuel.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ticket_pdf',
            field=models.FileField(blank=True, help_text='Version ticket simplifiée.', null=True, upload_to='reservations/tickets/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_paiement',
            field=models.CharField(choices=[('UNIQUE', 'Paiement unique'), ('MENSUEL', 'Paiement mensuel')], default='UNIQUE', max_length=12),
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_entree_1', models.ImageField(blank=True, null=True, upload_to='etats_des_lieux/')),
                ('photo_entree_2', models.ImageField(blank=True, null=True, upload_to='etats_des_lieux/')),
                ('photo_sortie_1', models.ImageField(blank=True, null=True, upload_to='etats_des_lieux/')),
                ('photo_sortie_2', models.ImageField(blank=True, null=True, upload_to='etats_des_lieux/')),
                ('commentaire_proprietaire', models.TextField(blank=True)),
                ('commentaire_commercant', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_des_lieux', to='core.reservation')),
            ],
            options={
                'verbose_name': 'état des lieux',
                'verbose_name_plural': 'états des lieux',
            },
        ),
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu')], default='OUVERT', max_length=12)),
                ('decision_admin', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='core.reservation')),
            ],
            options={
                'verbose_name': 'litige',
                'verbose_name_plural': 'litiges',
                'ordering': ['-created_at'],
            },
        ),
    ]
