# Generated by Django 5.2.12 on 2026-04-01 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_entrepot_boost_expires_at_entrepot_is_boosted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='code_parrainage',
            field=models.CharField(blank=True, help_text='Code unique de parrainage partagé à l’inscription.', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EntrepotIndisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('raison', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='core.entrepot')),
            ],
            options={
                'verbose_name': 'indisponibilité entrepôt',
                'verbose_name_plural': 'indisponibilités entrepôt',
                'ordering': ['-date_debut'],
            },
        ),
    ]
