# Generated by Django 5.2.12 on 2026-04-01 09:56

import core.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usercustom_code_parrainage_usercustom_parrain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='numero_momo',
            field=models.CharField(blank=True, help_text='Numéro Mobile Money (format international, ex. +229...).', max_length=24, validators=[core.models.validate_telephone_e164]),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='reseau_momo',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Money')], help_text='Réseau Mobile Money par défaut.', max_length=8),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='solde_parrainage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumul des gains de parrainage.', max_digits=12),
        ),
    ]
