# Generated by Django 5.2.12 on 2026-04-01 10:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usercustom_numero_momo_usercustom_reseau_momo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gain_parrainage_verse',
            field=models.BooleanField(default=False, help_text='Empêche de verser plusieurs fois la récompense de parrainage.'),
        ),
        migrations.CreateModel(
            name='ParrainageGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('filleul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains_generees', to=settings.AUTH_USER_MODEL)),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains_parrainage', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gain_parrainage', to='core.reservation')),
            ],
            options={
                'verbose_name': 'gain de parrainage',
                'verbose_name_plural': 'gains de parrainage',
                'ordering': ['-created_at'],
            },
        ),
    ]
