# Generated by Django 5.2.12 on 2026-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reservation_gain_parrainage_verse_parrainagegain'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='can_post_announcements',
            field=models.BooleanField(default=False, help_text='Active les fonctionnalités propriétaire sans changer de compte.'),
        ),
    ]
