# Generated by Django 5.2.12 on 2026-04-01 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_usercustom_can_post_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='core.entrepot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favori',
                'verbose_name_plural': 'favoris',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'entrepot'), name='unique_favori_user_entrepot')],
            },
        ),
    ]
